# Deep Learning Smartphone Activity Detector

http://archive.ics.uci.edu/ml/datasets/Smartphone-Based+Recognition+of+Human+Activities+and+Postural+Transitions

### Objective
### Predict human activity using smartphone sensor data

## Data Pre-Processing
### Note: This dataset has already been scaled

In [1]:
import os
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Training Data Paths
X_training_data = os.path.join("data", "Resources", "Train", "X_train.txt")
y_training_data = os.path.join("data", "Resources", "Train", "y_train.txt")

In [4]:
# Testing Data Paths
X_testing_data = os.path.join("data", "Resources", "Test", "X_test.txt")
y_testing_data = os.path.join("data", "Resources", "Test", "y_test.txt")

In [5]:
# Read the training data into a dataframe
X_train_df = pd.read_csv(
    X_training_data, delimiter=" ", skiprows=1, header=None)
X_train_df.head()

0         1         2         3         4         5         6    \
0  0.039480 -0.002131 -0.029067 -0.998348 -0.982945 -0.971273 -0.998702   
1  0.039978 -0.005153 -0.022651 -0.995482 -0.977314 -0.984760 -0.996415   
2  0.039785 -0.011809 -0.028916 -0.996194 -0.988569 -0.993256 -0.996994   
3  0.038758 -0.002289 -0.023863 -0.998241 -0.986774 -0.993115 -0.998216   
4  0.038988  0.004109 -0.017340 -0.997438 -0.993485 -0.996692 -0.997522   

        7         8         9    ...       551       552       553       554  \
0 -0.983315 -0.974000 -0.802537  ...  0.202804 -0.603199 -0.860677  0.053477   
1 -0.975835 -0.985973 -0.798477  ...  0.440079 -0.404427 -0.761847 -0.118559   
2 -0.988526 -0.993135 -0.798477  ...  0.430891 -0.138373 -0.491604 -0.036788   
3 -0.986479 -0.993825 -0.801982  ...  0.137735 -0.366214 -0.702490  0.123320   
4 -0.993494 -0.996916 -0.801982  ...  0.074999 -0.554902 -0.844224  0.082632   

        555       556       557       558       559       560  
0 -0.007435 -0.732626  0.703511 -0.845092  0.180261 -0.047436  
1  0.177899  0.100699  0.808529 -0.849230  0.180610 -0.042271  
2 -0.012892  0.640011 -0.485366 -0.848947  0.181907 -0.040826  
3  0.122542  0.693578 -0.615971 -0.848164  0.185124 -0.037080  
4 -0.143439  0.275041 -0.368224 -0.849927  0.184795 -0.035326  

[5 rows x 561 columns]

In [6]:
# Convert the dataframe to a numpy array for Keras
X_train = X_train_df.values

In [7]:
X_train

array([[ 0.03948004, -0.00213128, -0.02906736, ..., -0.8450924 ,
         0.18026111, -0.04743634],
       [ 0.03997778, -0.00515272, -0.02265071, ..., -0.84923013,
         0.18060956, -0.04227136],
       [ 0.03978456, -0.01180878, -0.02891578, ..., -0.84894659,
         0.18190709, -0.04082622],
       ...,
       [ 0.03745094, -0.00272442,  0.02100941, ..., -0.77956634,
         0.24912145,  0.04707077],
       [ 0.04401105, -0.00453578, -0.0512422 , ..., -0.78560327,
         0.24640867,  0.03170003],
       [ 0.06895376,  0.00181032, -0.08032343, ..., -0.78369253,
         0.24678499,  0.04298129]])

In [8]:
# Read in the training labels as a dataframe
y_train_df = pd.read_csv(y_training_data)

# One-hot encode the integer labels
# 1 WALKING
# 2 WALKING_UPSTAIRS
# 3 WALKING_DOWNSTAIRS
# 4 SITTING
# 5 STANDING
# 6 LAYING
# 7 STAND_TO_SIT
# 8 SIT_TO_STAND
# 9 SIT_TO_LIE
# 10 LIE_TO_SIT
# 11 STAND_TO_LIE
# 12 LIE_TO_STAND

y_train = to_categorical(y_train_df)
y_train[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [9]:
#y_train_df.head()

In [10]:
# Read the testing data
X_test_df = pd.read_csv(X_testing_data, delimiter=" ", skiprows=1, header=None)
X_test = X_test_df.values
X_test.shape

(3161, 561)

In [11]:
# Read the testing labels
y_test_df = pd.read_csv(y_testing_data)
# One-hot encode the integer labels
y_test = to_categorical(y_test_df)
y_test.shape

(3161, 13)

# Build a Deep Neural Network

In [12]:
# Create an empty sequential model
model = Sequential()

In [13]:
X_train.shape

(7766, 561)

In [14]:
# Add the first layer where the input dimensions are the 561 columns of the training data
# it means the first dense layer one has 561 input as X_train.shape[1], and 100 out put
model.add(Dense(100, activation='relu', input_dim=X_train.shape[1]))

In [15]:
# Add a second hidden layer
# the 2nd dense layer has 100 output and don't need to mention how many inputs, since it is connect to the 1st one(100)
model.add(Dense(100, activation='relu'))

In [16]:
# The output layer has 13 columns that are one-hot encoded
y_train.shape

(7766, 13)

In [17]:
# Add output layer
# the last dense with outputs 13 as y_train.shape[1], and don't need to mention the input as 100, as connected with 2nd dense
model.add(Dense(y_train.shape[1], activation="softmax"))

In [18]:
# Compile the model using categorical_crossentropy for the loss function, the adam optimizer,
# and add accuracy to the training metrics
model.compile(loss="categorical_crossentropy",
              optimizer="adam", metrics=['accuracy'])

In [19]:
# Use the training data to fit (train) the model
#verbose = 2, one line shown per epoch i.e. epoch no./total no. of epochs

model.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
243/243 - 1s - loss: 0.5710 - accuracy: 0.7964
Epoch 2/100
243/243 - 0s - loss: 0.1964 - accuracy: 0.9266
Epoch 3/100
243/243 - 0s - loss: 0.1530 - accuracy: 0.9396
Epoch 4/100
243/243 - 0s - loss: 0.1277 - accuracy: 0.9495
Epoch 5/100
243/243 - 0s - loss: 0.1175 - accuracy: 0.9509
Epoch 6/100
243/243 - 0s - loss: 0.1032 - accuracy: 0.9601
Epoch 7/100
243/243 - 0s - loss: 0.0872 - accuracy: 0.9670
Epoch 8/100
243/243 - 0s - loss: 0.0786 - accuracy: 0.9696
Epoch 9/100
243/243 - 0s - loss: 0.0798 - accuracy: 0.9727
Epoch 10/100
243/243 - 0s - loss: 0.0865 - accuracy: 0.9659
Epoch 11/100
243/243 - 0s - loss: 0.0719 - accuracy: 0.9715
Epoch 12/100
243/243 - 0s - loss: 0.0799 - accuracy: 0.9697
Epoch 13/100
243/243 - 0s - loss: 0.0773 - accuracy: 0.9704
Epoch 14/100
243/243 - 0s - loss: 0.0656 - accuracy: 0.9731
Epoch 15/100
243/243 - 0s - loss: 0.0634 - accuracy: 0.9764
Epoch 16/100
243/243 - 0s - loss: 0.0594 - accuracy: 0.9770
Epoch 17/100
243/243 - 0s - loss: 0.0634 - accura

# Save the Trained Model

In [20]:
# Save the model
model.save("smartphone_trained.h5")

# Evaluate the Model

In [21]:
# Load the model
from tensorflow.keras.models import load_model
model = load_model("smartphone_trained.h5")

In [22]:
# Evaluate the model using the training data
model_loss, model_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

99/99 - 0s - loss: 0.4185 - accuracy: 0.9279
Loss: 0.4184665381908417, Accuracy: 0.9278709292411804


In [31]:
# Grab just one data point to test with
test = np.expand_dims(X_test[:5], axis=0)
test.shape

(1, 5, 561)

In [32]:
# Make a prediction. The result should be 5 - STANDING
print(f"Predicted class: {model.predict_classes(test)}")

Predicted class: [[5 5 5 5 5]]


In [33]:
#The updated way to predict
print(f"Predicted class: {np.argmax(model.predict(test), axis=-1)}")

Predicted class: [[5 5 5 5 5]]


In [34]:
# the correspondent X_test[0] is y_test[0]
y_test[:5]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [37]:
len(y_test[:5])

5

In [44]:
print([argmax(i) for i in y_test[:5]])

[5, 5, 5, 5, 5]


In [40]:
from numpy import argmax
for i in y_test[:5]:
    y_predicted = int(argmax(i))
    print(y_predicted)

5
5
5
5
5
