## Numpy and Array

In [1]:
import numpy as np


In [2]:
np.array(['a','b','c','d','e'],ndmin=2)

array([['a', 'b', 'c', 'd', 'e']], dtype='<U1')

In [3]:
s= np.array([['a','b'],['c','d','e']]) 

In [4]:
s.ndim

1

In [5]:
np.array(['a','b','c','d','e'],ndmin=1)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [6]:
a=np.array(['a','b',2,'3.0'])
a

array(['a', 'b', '2', '3.0'], dtype='<U3')

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
a.dtype

dtype('<U3')

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [14]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# -1 means other dimension decided by system
# b.reshape(3, -1)

In [16]:
b.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# as follows, :2 means all rows, ::2 means for each column, from the begining to the end, step 2
b[:2,::2]

array([[1, 3],
       [4, 6]])

In [18]:
# another index sample, the first 0:2 for rows slice, the secon 0:2 for column slice:
b[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [19]:
b[0:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[:, 0:2]

array([[1, 2],
       [4, 5]])