## Numpy and Array

In [2]:
import numpy as np


In [3]:
np.array(['a','b','c','d','e'],ndmin=2)

array([['a', 'b', 'c', 'd', 'e']], dtype='<U1')

In [4]:
np.array([['a','b'],['c','d','e']]) 

array([list(['a', 'b']), list(['c', 'd', 'e'])], dtype=object)

In [5]:
np.array(['a','b','c','d','e'],ndmin=1)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [6]:
a=np.array(['a','b',2,'3.0'])
a

array(['a', 'b', '2', '3.0'], dtype='<U3')

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
a.dtype

dtype('<U3')

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [13]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# -1 means other dimension decided by system
# b.reshape(3, -1)

In [19]:
# b.reshape(2, -1)

In [20]:
b[:2,::2]

array([[1, 3],
       [4, 6]])